export const BOARD_SET = 'BOARD_SET'
export const CLASS_SET = 'CLASS_SET'
export const SUBJECT_SET = 'SUBJECT_SET'
export const CHAPTER_SET = 'CHAPTER_SET'
export const CONTENT_SET = 'CONTENT_SET'
export const ROLE_SET = 'ROLE_SET'
